-- ══════════════════════════════════════════════════════════════════
--  ⚠️  ARCHIVO ELIMINADO POR SEGURIDAD — NO CONTIENE DATOS  ⚠️
--
--  Este archivo contenía datos PII (información de identificación
--  personal) de efectivos policiales: nombres, domicilios,
--  teléfonos, emails, números de armas y chalecos.
--
--  Fue detectado como vulnerabilidad CRÍTICA (VULN-02) en la
--  auditoría de seguridad del 2026-06-07.
--
--  LOS DATOS FUERON ELIMINADOS DE ESTE ARCHIVO.
--
--  ⚡ ACCIÓN PENDIENTE:
--     El archivo fue commiteado previamente con los datos reales.
--     Limpiar el historial de git siguiendo las instrucciones en:
--     INSTRUCCIONES_LIMPIEZA_GIT.md
--
--  ✅ Para cargar el personal, usar exclusivamente:
--     Supabase Dashboard → Table Editor → personal → Insert rows
--     O via API admin (service_role) desde un entorno seguro.
-- ══════════════════════════════════════════════════════════════════
